development:
  API_KEY: ENV["API_KEY"]
  API_SECRET: ENV["API_SECRET"]
  GOOG_API_KEY: ENV["GOOG_API_KEY"]

test:
  API_KEY: ENV["API_KEY"]
  API_SECRET: ENV["API_SECRET"]
  GOOG_API_KEY: ENV["GOOG_API_KEY"]

production:
  API_KEY: ENV["API_KEY"]
  API_SECRET: ENV["API_SECRET"]
  GOOG_API_KEY: ENV["GOOG_API_KEY"]
